// Datos demo de Rappi Crew. Todo es ficticio: personas, historias, métricas y beneficios.

import type {
  Benefit,
  ChatMessage,
  Cluster,
  Copilot,
  Experience,
  HelpRequest,
  Invitation,
  Mentee,
  OnboardingStep,
  Protocol,
  RiderProfile,
  TimelineEvent,
  VoiceStory,
} from './types';

export const DEMO_RIDER: RiderProfile = {
  id: 'r-valentina',
  name: 'Valentina Ruiz',
  firstName: 'Valentina',
  initials: 'VR',
  color: '#FF5B35',
  vehicle: 'moto',
  zone: 'Chapinero',
  schedule: ['tarde', 'noche'],
  joinedDaysAgo: 9,
  deliveries: 23,
};

export const DEMO_ADMIN = {
  name: 'Laura Méndez',
  firstName: 'Laura',
  initials: 'LM',
  team: 'Equipo Rappi Crew · Operaciones',
};

export const COPILOTS: Copilot[] = [
  {
    id: 'c-andres',
    name: 'Andrés Rojas',
    firstName: 'Andrés',
    initials: 'AR',
    color: '#2A78D6',
    yearsOnPlatform: 3,
    monthsOnPlatform: 38,
    deliveries: 6480,
    vehicle: 'moto',
    zone: 'Chapinero',
    nearbyZones: ['Teusaquillo', 'Usaquén'],
    availability: 'alta',
    schedule: ['tarde', 'noche'],
    bio: 'Arranqué sin conocer las calles de Chapinero. Hoy me sé los atajos, las porterías difíciles y cómo no perder la calma cuando un pedido se complica.',
    specialties: ['Clientes que no responden', 'Edificios con portería', 'Horas pico'],
    accompanied: 14,
    experiencesShared: 27,
    protocolsOriginated: ['p-014', 'p-011'],
    badges: ['Copiloto fundador', 'Voz de la Crew', 'Calma en hora pico'],
    status: 'activo',
    responseTime: 'Suele responder en ~15 min',
  },
  {
    id: 'c-luisa',
    name: 'Luisa Fernanda Gómez',
    firstName: 'Luisa',
    initials: 'LG',
    color: '#12B07A',
    yearsOnPlatform: 2,
    monthsOnPlatform: 27,
    deliveries: 4120,
    vehicle: 'bici',
    zone: 'Teusaquillo',
    nearbyZones: ['Chapinero', 'Centro'],
    availability: 'media',
    schedule: ['manana', 'tarde'],
    bio: 'Ruedo en bici y conozco las ciclorrutas mejor que mi casa. Me gusta ayudar a organizar el día para no quemarse.',
    specialties: ['Rutas en bici', 'Organizar turnos', 'Pedidos grandes'],
    accompanied: 9,
    experiencesShared: 18,
    protocolsOriginated: ['p-009'],
    badges: ['Ruta segura', 'Posta de oro'],
    status: 'activo',
    responseTime: 'Suele responder en ~30 min',
  },
  {
    id: 'c-camilo',
    name: 'Camilo Pérez',
    firstName: 'Camilo',
    initials: 'CP',
    color: '#6D55E0',
    yearsOnPlatform: 4,
    monthsOnPlatform: 51,
    deliveries: 9210,
    vehicle: 'moto',
    zone: 'Usaquén',
    nearbyZones: ['Cedritos', 'Chapinero'],
    availability: 'baja',
    schedule: ['noche', 'fin_de_semana'],
    bio: 'Llevo cuatro años en la calle. Lo que más me preguntan: qué hacer cuando te mandan lejos y cómo cuidarse de noche.',
    specialties: ['Entregas lejanas', 'Turno noche', 'Seguridad'],
    accompanied: 21,
    experiencesShared: 34,
    protocolsOriginated: ['p-017'],
    badges: ['Copiloto fundador', 'Guardián nocturno'],
    status: 'activo',
    responseTime: 'Suele responder en ~1 h',
  },
  {
    id: 'c-marta',
    name: 'Marta Silva',
    firstName: 'Marta',
    initials: 'MS',
    color: '#F5A300',
    yearsOnPlatform: 1,
    monthsOnPlatform: 19,
    deliveries: 2890,
    vehicle: 'carro',
    zone: 'Salitre',
    nearbyZones: ['Teusaquillo', 'Kennedy'],
    availability: 'alta',
    schedule: ['manana', 'fin_de_semana'],
    bio: 'Hago mercados grandes en carro. Aprendí a hablar con las tiendas para que el pedido salga completo a la primera.',
    specialties: ['Mercados grandes', 'Relación con tiendas'],
    accompanied: 6,
    experiencesShared: 12,
    protocolsOriginated: [],
    badges: ['Aliada de tiendas'],
    status: 'activo',
    responseTime: 'Suele responder en ~20 min',
  },
];

export const INITIAL_ONBOARDING: OnboardingStep[] = [
  {
    id: 'perfil',
    title: 'Completa tu perfil y zona habitual',
    detail: 'Así encontramos un Copiloto cerca de ti.',
    done: true,
    href: '/mi-copiloto/match',
  },
  {
    id: 'copiloto',
    title: 'Conoce a tu Copiloto',
    detail: 'Un Rappitendero con experiencia que decidió acompañarte.',
    done: true,
    href: '/mi-copiloto',
  },
  {
    id: 'chat',
    title: 'Habla con tu Copiloto',
    detail: 'Preséntate y cuéntale cómo te fue en tus primeros pedidos.',
    done: false,
    href: '/mi-copiloto/chat',
  },
  {
    id: 'protocolo',
    title: 'Lee tu primer Protocolo Crew',
    detail: 'Soluciones validadas por Rappi para situaciones reales.',
    done: false,
    href: '/protocolos/p-014',
  },
  {
    id: 'beneficios',
    title: 'Explora los Beneficios Crew',
    detail: 'Movilidad, salud, familia y aprendizaje.',
    done: false,
    href: '/beneficios',
  },
  {
    id: 'posta',
    title: 'Pasa tu primera Posta',
    detail: 'Lo que aprendes también le sirve a quien viene detrás.',
    done: false,
    href: '/pasa-la-posta',
  },
];

export const INITIAL_THREADS: Record<string, ChatMessage[]> = {
  'th-valentina': [
    {
      id: 'm1',
      from: 'system',
      text: 'Andrés aceptó acompañarte como Copiloto de forma voluntaria. Recuerda: comparte experiencia práctica, no es soporte oficial.',
      at: '2026-09-21T15:02:00',
    },
    {
      id: 'm2',
      from: 'copiloto',
      text: '¡Hola Valentina! Soy Andrés, llevo 3 años moviéndome por Chapinero. Cualquier duda de la calle, me escribes 🙌',
      at: '2026-09-21T15:10:00',
    },
    {
      id: 'm3',
      from: 'nuevo',
      text: 'Hola Andrés, gracias. Ayer me tocó un edificio sin portería y el cliente no contestaba 😅',
      at: '2026-09-21T19:40:00',
    },
    {
      id: 'm4',
      from: 'copiloto',
      text: 'Nos ha pasado a todos. Hay un Protocolo Crew justo para eso, el #014. Míralo y si algo no te cuadra lo hablamos.',
      at: '2026-09-21T19:52:00',
    },
  ],
  'th-sebastian': [
    {
      id: 's1',
      from: 'system',
      text: 'Aceptaste acompañar a Sebastián. Puedes pausar o dejar de participar cuando quieras.',
      at: '2026-09-12T10:00:00',
    },
    {
      id: 's2',
      from: 'nuevo',
      text: 'Parce, ¿cómo hago cuando la tienda dice que el pedido no está listo y ya llevo 20 minutos?',
      at: '2026-09-27T13:15:00',
    },
  ],
  'th-daniela': [
    {
      id: 'd1',
      from: 'system',
      text: 'Aceptaste acompañar a Daniela. Puedes pausar o dejar de participar cuando quieras.',
      at: '2026-09-02T09:00:00',
    },
    {
      id: 'd2',
      from: 'copiloto',
      text: '¡Qué bien esa primera semana, Daniela! Ya te mueves como si llevaras meses.',
      at: '2026-09-25T18:30:00',
    },
    {
      id: 'd3',
      from: 'nuevo',
      text: '¡Gracias! Lo del protocolo de tienda me salvó ayer.',
      at: '2026-09-25T18:41:00',
    },
  ],
};

export const COPILOT_REPLIES = [
  'Buena pregunta. Lo que a mí me funciona: mantener la calma, dejar todo registrado en el chat del pedido y revisar el Protocolo Crew del tema.',
  'Te cuento cómo lo hago yo, pero ojo: lo oficial siempre es el protocolo validado o el soporte de Rappi.',
  'Eso me pasó mil veces al principio. Tranqui, vas bien. ¿Quieres que lo revisemos con calma en tu próximo descanso?',
  '¡Eso! Así se aprende. Si te pasa algo nuevo, compártelo en Pasa la Posta, le sirve a toda la Crew.',
];

export const TIMELINE: TimelineEvent[] = [
  {
    id: 't1',
    date: '2026-09-20',
    title: 'Match con Andrés',
    detail: 'Coincidencia por zona (Chapinero), vehículo (moto) y horario (tarde/noche).',
    kind: 'inicio',
  },
  {
    id: 't2',
    date: '2026-09-21',
    title: 'Primera conversación',
    detail: 'Andrés te dio la bienvenida y compartió su experiencia en Chapinero.',
    kind: 'chat',
  },
  {
    id: 't3',
    date: '2026-09-21',
    title: 'Te recomendó el Protocolo Crew #014',
    detail: 'Cliente no responde: qué hacer paso a paso.',
    kind: 'protocolo',
  },
  {
    id: 't4',
    date: '2026-09-25',
    title: '20 entregas completadas',
    detail: 'Primer hito de tu primera semana en la calle.',
    kind: 'hito',
  },
];

export const PROTOCOLS: Protocol[] = [
  {
    id: 'p-014',
    number: 14,
    title: 'Cliente no responde',
    category: 'cliente_no_responde',
    summary: 'Qué hacer cuando llegas al punto de entrega y el cliente no contesta llamadas ni chat.',
    problem:
      'Llegas a la dirección de entrega y el cliente no responde llamadas ni mensajes. No sabes cuánto esperar ni qué hacer con el pedido.',
    situation:
      'Muy común en edificios con portería, conjuntos cerrados y en horas pico (12–2 p. m. y 7–9 p. m.). Genera estrés, pérdida de tiempo y dudas sobre si el pedido cuenta.',
    steps: [
      'Confirma en el mapa que estás en la dirección exacta y revisa las notas del pedido (torre, apartamento, referencias).',
      'Escribe al cliente por el chat del pedido: "Hola, soy tu Rappitendero, ya estoy en la entrada". Así queda registro.',
      'Llama desde la app. Si no contesta, espera 2 minutos e intenta una segunda llamada.',
      'Si hay portería, pide que anuncien el pedido con el nombre y número de apartamento.',
      'Si tras el tiempo de espera indicado en la app el cliente sigue sin responder, usa la opción "Cliente no responde" en la app para reportarlo.',
      'Sigue las instrucciones que te indique la app sobre el pedido. No lo dejes en un lugar sin autorización.',
    ],
    escalate: [
      'Si el pedido contiene productos de alto valor o medicamentos.',
      'Si la dirección no existe o es un lugar inseguro.',
      'Si la app no muestra la opción de reporte después del tiempo de espera.',
    ],
    origin:
      'Construido a partir de 37 experiencias reales compartidas por Rappitenderos de Chapinero, Usaquén y Teusaquillo, y revisado por el equipo de Operaciones de Rappi.',
    contributors: ['Andrés Rojas', 'Camilo Pérez', 'Juliana Torres'],
    experiencesCount: 37,
    updatedAt: '2026-09-18',
    status: 'publicado',
    views: 1842,
    helpful: 412,
    readMinutes: 3,
    clusterId: 'cl-1',
  },
  {
    id: 'p-009',
    number: 9,
    title: 'Pedido incompleto en la tienda',
    category: 'problema_pedido',
    summary: 'Cómo actuar cuando al recoger faltan productos o no coinciden con el pedido.',
    problem: 'Al recoger, la bolsa no tiene todos los productos del pedido o hay cambios que el cliente no aprobó.',
    situation:
      'Pasa sobre todo en mercados y farmacias con alta demanda. Si sales sin revisar, el problema llega a la puerta del cliente.',
    steps: [
      'Antes de salir, compara la bolsa con el detalle del pedido en la app.',
      'Si falta algo, avísale amablemente al personal de la tienda y pide que lo verifiquen.',
      'Si el producto no está disponible, registra la novedad en la app para que el cliente sea notificado.',
      'Espera la confirmación en la app antes de continuar hacia la entrega.',
      'Al entregar, menciona al cliente los cambios que ya fueron notificados.',
    ],
    escalate: [
      'Si la tienda se niega a verificar el pedido.',
      'Si la app no permite registrar la novedad.',
    ],
    origin: 'Nació de 22 experiencias de Rappitenderos en mercados y farmacias, validadas por Rappi.',
    contributors: ['Luisa Fernanda Gómez', 'Marta Silva'],
    experiencesCount: 22,
    updatedAt: '2026-09-02',
    status: 'publicado',
    views: 1210,
    helpful: 288,
    readMinutes: 2,
    clusterId: 'cl-2',
  },
  {
    id: 'p-011',
    number: 11,
    title: 'La tienda demora el pedido',
    category: 'problema_tienda',
    summary: 'Qué hacer si el pedido no está listo y la espera se alarga.',
    problem: 'Llegas a la tienda y el pedido no está listo. La espera se alarga sin información clara.',
    situation:
      'Frecuente en restaurantes en horas pico y fines de semana. La incertidumbre hace que muchos nuevos no sepan si esperar o no.',
    steps: [
      'Preséntate en el punto de recogida con el código del pedido visible.',
      'Pregunta con amabilidad el tiempo estimado y confírmalo en el chat del pedido.',
      'Si la espera supera el tiempo que indica la app, registra la demora desde la opción correspondiente.',
      'Mientras esperas, ubícate en un lugar que no bloquee la entrada.',
    ],
    escalate: [
      'Si la tienda indica que el pedido no será preparado.',
      'Si recibes un trato irrespetuoso.',
    ],
    origin: 'Basado en 29 experiencias de Rappitenderos en zonas de restaurantes, validado por Rappi.',
    contributors: ['Andrés Rojas', 'Sebastián Castro'],
    experiencesCount: 29,
    updatedAt: '2026-08-27',
    status: 'publicado',
    views: 964,
    helpful: 201,
    readMinutes: 2,
    clusterId: 'cl-3',
  },
  {
    id: 'p-017',
    number: 17,
    title: 'Entrega fuera de tu zona habitual',
    category: 'demasiado_lejos',
    summary: 'Cómo manejar un pedido que te lleva lejos de la zona donde sueles moverte.',
    problem: 'Te asignan una entrega que te aleja mucho de tu zona habitual y no sabes cómo volver o si te conviene.',
    situation:
      'Ocurre al final del turno o en zonas con poca oferta de Rappitenderos. Muchos nuevos no conocen las opciones de configuración de zona.',
    steps: [
      'Antes de aceptar, revisa la distancia estimada y el punto de entrega en la app.',
      'Revisa en tu configuración las zonas en las que quieres recibir pedidos.',
      'Si ya aceptaste, planea la ruta de regreso antes de salir del punto de entrega.',
      'Comparte tu ubicación en tiempo real con alguien de confianza si es de noche.',
    ],
    escalate: [
      'Si te sientes inseguro en la zona de entrega.',
      'Si la dirección real no coincide con la del pedido.',
    ],
    origin: 'Construido con 18 experiencias de Rappitenderos del turno noche, revisado por Rappi.',
    contributors: ['Camilo Pérez'],
    experiencesCount: 18,
    updatedAt: '2026-09-10',
    status: 'publicado',
    views: 731,
    helpful: 156,
    readMinutes: 3,
    clusterId: 'cl-4',
  },
  {
    id: 'p-021',
    number: 21,
    title: 'Un incentivo no se reflejó',
    category: 'problema_incentivo',
    summary: 'Pasos para revisar y reportar cuando algo no aparece como esperabas.',
    problem: 'Cumpliste las condiciones de una campaña, pero no ves el reflejo en tu resumen.',
    situation:
      'Genera desconfianza, sobre todo en las primeras semanas. Muchas veces es un tema de tiempos de actualización.',
    steps: [
      'Revisa las condiciones exactas de la campaña en la sección oficial de la app.',
      'Verifica el período de actualización indicado (algunas se reflejan días después).',
      'Si pasado ese período no aparece, repórtalo desde el centro de ayuda con el nombre de la campaña.',
      'Guarda capturas de tu resumen como respaldo.',
    ],
    escalate: ['Si tras el período de actualización no hay respuesta del centro de ayuda.'],
    origin: 'Nació de 15 casos reportados en "Necesito una mano", validado por Rappi.',
    contributors: ['Juliana Torres'],
    experiencesCount: 15,
    updatedAt: '2026-09-14',
    status: 'publicado',
    views: 588,
    helpful: 97,
    readMinutes: 2,
    clusterId: 'cl-5',
  },
  {
    id: 'p-006',
    number: 6,
    title: 'Conducir bajo lluvia fuerte',
    category: 'otro',
    summary: 'Recomendaciones de la Crew para moverte con seguridad cuando llueve.',
    problem: 'Aguaceros fuertes que reducen visibilidad y aumentan el riesgo en la vía.',
    situation: 'Temporada de lluvias: calles resbalosas, huecos ocultos y menos visibilidad.',
    steps: [
      'Reduce la velocidad y aumenta la distancia con otros vehículos.',
      'Evita pasar por charcos grandes: pueden ocultar huecos.',
      'Protege el pedido con la bolsa impermeable antes de salir.',
      'Si la lluvia es muy fuerte, busca un lugar seguro y avisa al cliente por el chat del pedido.',
    ],
    escalate: ['Si hay inundaciones o vías cerradas en la ruta.'],
    origin: 'Recomendaciones reunidas de 41 experiencias de la Crew, revisadas por Rappi.',
    contributors: ['Luisa Fernanda Gómez', 'Camilo Pérez', 'Mateo León'],
    experiencesCount: 41,
    updatedAt: '2026-07-30',
    status: 'publicado',
    views: 2104,
    helpful: 530,
    readMinutes: 2,
  },
  {
    id: 'p-019',
    number: 19,
    title: 'Dirección incorrecta en conjunto cerrado',
    category: 'problema_pedido',
    summary: 'Cuando la torre o el apartamento no existen dentro del conjunto.',
    problem: 'Llegas al conjunto y la torre o el apartamento indicado no existe.',
    situation: 'Conjuntos grandes con numeraciones confusas.',
    steps: [
      'Consulta en portería si reconocen el nombre del cliente.',
      'Escribe al cliente por el chat del pedido para confirmar la dirección.',
      'Si la dirección cambia, pide al cliente que la actualice en la app.',
    ],
    escalate: ['Si el cliente pide entregar en otra dirección fuera del conjunto.'],
    origin: 'Basado en 12 experiencias de Rappitenderos de Suba y Cedritos.',
    contributors: ['Mateo León'],
    experiencesCount: 12,
    updatedAt: '2026-09-24',
    status: 'aprobado',
    views: 0,
    helpful: 0,
    readMinutes: 2,
    clusterId: 'cl-6',
  },
  {
    id: 'p-023',
    number: 23,
    title: 'Pago en efectivo sin cambio',
    category: 'problema_pedido',
    summary: 'Qué hacer cuando el cliente paga en efectivo y no tienes cambio.',
    problem: 'El cliente paga con un billete grande y no tienes cómo dar el cambio.',
    situation: 'Primeras semanas, cuando aún no se tiene sencillo.',
    steps: ['Pregunta al cliente si tiene un monto más cercano.', 'Consulta las opciones de pago disponibles en la app.'],
    escalate: ['Si el cliente se niega a pagar.'],
    origin: 'En construcción a partir de 9 experiencias recientes.',
    contributors: ['Sebastián Castro'],
    experiencesCount: 9,
    updatedAt: '2026-09-26',
    status: 'borrador',
    views: 0,
    helpful: 0,
    readMinutes: 2,
    clusterId: 'cl-7',
  },
  {
    id: 'p-024',
    number: 24,
    title: 'Mascota agresiva en la entrega',
    category: 'otro',
    summary: 'Cómo protegerte si hay un perro suelto en el punto de entrega.',
    problem: 'Un perro suelto o agresivo impide acercarte con seguridad.',
    situation: 'Casas y conjuntos con zonas comunes abiertas.',
    steps: [
      'No te acerques. Mantén el vehículo entre tú y el animal.',
      'Escribe al cliente pidiendo que salga o asegure a la mascota.',
      'Espera en un lugar seguro hasta que el cliente confirme.',
    ],
    escalate: ['Si sufres una mordedura o lesión.'],
    origin: 'Propuesto a partir de 11 experiencias de la Crew.',
    contributors: ['Daniela Ortiz', 'Camilo Pérez'],
    experiencesCount: 11,
    updatedAt: '2026-09-27',
    status: 'en_validacion',
    views: 0,
    helpful: 0,
    readMinutes: 2,
  },
];

export const EXPERIENCES: Experience[] = [
  {
    id: 'e-1',
    author: 'Andrés Rojas',
    initials: 'AR',
    color: '#2A78D6',
    authorRole: 'copiloto',
    months: 38,
    zone: 'Chapinero',
    category: 'cliente_no_responde',
    text: 'Siempre escribo por el chat del pedido antes de llamar. Si después hay un reclamo, queda todo registrado y te ahorras un mal rato.',
    createdAt: '2026-09-26T18:20:00',
    thanks: 48,
    status: 'en_protocolo',
    clusterId: 'cl-1',
  },
  {
    id: 'e-2',
    author: 'Luisa Fernanda Gómez',
    initials: 'LG',
    color: '#12B07A',
    authorRole: 'copiloto',
    months: 27,
    zone: 'Teusaquillo',
    category: 'problema_pedido',
    text: 'Revisar la bolsa antes de salir de la tienda me cambió la vida. Dos minutos ahí te ahorran veinte en la puerta del cliente.',
    createdAt: '2026-09-25T12:05:00',
    thanks: 36,
    status: 'en_protocolo',
    clusterId: 'cl-2',
  },
  {
    id: 'e-3',
    author: 'Camilo Pérez',
    initials: 'CP',
    color: '#6D55E0',
    authorRole: 'copiloto',
    months: 51,
    zone: 'Usaquén',
    category: 'demasiado_lejos',
    text: 'De noche, antes de aceptar un pedido lejano, pienso en cómo voy a volver. Si la ruta de regreso no me convence, prefiero ajustar mis zonas.',
    createdAt: '2026-09-24T22:10:00',
    thanks: 29,
    status: 'en_protocolo',
    clusterId: 'cl-4',
  },
  {
    id: 'e-4',
    author: 'Juliana Torres',
    initials: 'JT',
    color: '#E0301A',
    authorRole: 'rappitendero',
    months: 14,
    zone: 'Cedritos',
    category: 'problema_incentivo',
    text: 'Lo que me hubiera gustado saber: las campañas tienen fechas de actualización. Antes de preocuparte, revisa cuándo se reflejan.',
    createdAt: '2026-09-23T09:40:00',
    thanks: 22,
    status: 'en_protocolo',
    clusterId: 'cl-5',
  },
  {
    id: 'e-5',
    author: 'Mateo León',
    initials: 'ML',
    color: '#0A8F62',
    authorRole: 'rappitendero',
    months: 20,
    zone: 'Suba',
    category: 'problema_pedido',
    text: 'En los conjuntos de Suba la numeración es un laberinto. Pregunta en portería por el nombre del cliente, no solo por la torre.',
    createdAt: '2026-09-22T17:30:00',
    thanks: 18,
    status: 'agrupada',
    clusterId: 'cl-6',
  },
  {
    id: 'e-6',
    author: 'Sebastián Castro',
    initials: 'SC',
    color: '#F5A300',
    authorRole: 'nuevo',
    months: 1,
    zone: 'Chapinero',
    category: 'problema_tienda',
    text: 'Aprendí que preguntar con buena actitud en la tienda cambia todo. Me dieron el pedido antes porque saludé por el nombre.',
    createdAt: '2026-09-27T14:15:00',
    thanks: 11,
    status: 'nueva',
  },
  {
    id: 'e-7',
    author: 'Daniela Ortiz',
    initials: 'DO',
    color: '#C63010',
    authorRole: 'nuevo',
    months: 1,
    zone: 'Teusaquillo',
    category: 'otro',
    text: 'Un perro suelto me bloqueó una entrega. Escribí al cliente y salió a recibirme. No te arriesgues, espera.',
    createdAt: '2026-09-26T11:50:00',
    thanks: 14,
    status: 'agrupada',
  },
  {
    id: 'e-8',
    author: 'Kevin Martínez',
    initials: 'KM',
    color: '#1F62B5',
    authorRole: 'rappitendero',
    months: 9,
    zone: 'Kennedy',
    category: 'demasiado_lejos',
    text: 'Me mandaron de Kennedy hasta Usaquén a las 10 p. m. Ahora reviso la distancia antes de aceptar y configuro bien mis zonas.',
    createdAt: '2026-09-27T23:05:00',
    thanks: 9,
    status: 'nueva',
  },
  {
    id: 'e-9',
    author: 'Paola Rincón',
    initials: 'PR',
    color: '#5842C4',
    authorRole: 'rappitendero',
    months: 16,
    zone: 'Salitre',
    category: 'cliente_no_responde',
    text: 'Cuando hay portería, pido que anuncien con nombre y apartamento. El 80% de las veces el cliente baja enseguida.',
    createdAt: '2026-09-28T13:00:00',
    thanks: 7,
    status: 'nueva',
  },
  {
    id: 'e-10',
    author: 'Sebastián Castro',
    initials: 'SC',
    color: '#F5A300',
    authorRole: 'nuevo',
    months: 1,
    zone: 'Chapinero',
    category: 'problema_pedido',
    text: 'El cliente me pagó con un billete de 100 mil y no tenía cambio. Ahora salgo con sencillo desde casa.',
    createdAt: '2026-09-28T19:45:00',
    thanks: 5,
    status: 'agrupada',
    clusterId: 'cl-7',
  },
  {
    id: 'e-11',
    author: 'Natalia Vargas',
    initials: 'NV',
    color: '#12B07A',
    authorRole: 'rappitendero',
    months: 30,
    zone: 'Centro',
    category: 'problema_tienda',
    text: 'En el Centro hay locales donde el punto de recogida está por la parte de atrás. Pregunta antes de dar vueltas.',
    createdAt: '2026-09-28T10:20:00',
    thanks: 6,
    status: 'nueva',
  },
  {
    id: 'e-12',
    author: 'Kevin Martínez',
    initials: 'KM',
    color: '#1F62B5',
    authorRole: 'rappitendero',
    months: 9,
    zone: 'Kennedy',
    category: 'cliente_no_responde',
    text: 'Me pasó tres veces en la misma semana en conjuntos de Kennedy. Lo que ayuda: mensaje en el chat + esperar el tiempo que indica la app.',
    createdAt: '2026-09-29T08:30:00',
    thanks: 2,
    status: 'nueva',
  },
  {
    id: 'e-13',
    author: 'Paola Rincón',
    initials: 'PR',
    color: '#5842C4',
    authorRole: 'rappitendero',
    months: 16,
    zone: 'Centro',
    category: 'problema_tienda',
    text: 'Di tres vueltas a la manzana: la recogida era por el parqueadero y nadie lo decía. Ahora le pregunto al vigilante antes de buscar la puerta principal.',
    createdAt: '2026-09-28T16:40:00',
    thanks: 4,
    status: 'nueva',
  },
  {
    id: 'e-14',
    author: 'Kevin Martínez',
    initials: 'KM',
    color: '#1F62B5',
    authorRole: 'rappitendero',
    months: 9,
    zone: 'Salitre',
    category: 'problema_tienda',
    text: 'En centros comerciales el punto de recogida suele estar en el sótano o en una puerta de servicio. Revisar las notas de la tienda en la app me ahorra 10 minutos.',
    createdAt: '2026-09-29T09:10:00',
    thanks: 3,
    status: 'nueva',
  },
];

export const CLUSTERS: Cluster[] = [
  {
    id: 'cl-1',
    title: 'Cliente no responde en edificios con portería',
    category: 'cliente_no_responde',
    cases: 37,
    experienceIds: ['e-1'],
    status: 'publicado',
    protocolId: 'p-014',
    trend: -18,
    zones: ['Chapinero', 'Usaquén', 'Teusaquillo'],
    createdAt: '2026-08-30',
  },
  {
    id: 'cl-2',
    title: 'Pedidos incompletos en mercados',
    category: 'problema_pedido',
    cases: 22,
    experienceIds: ['e-2'],
    status: 'publicado',
    protocolId: 'p-009',
    trend: -9,
    zones: ['Teusaquillo', 'Salitre'],
    createdAt: '2026-08-10',
  },
  {
    id: 'cl-3',
    title: 'Demoras de tienda en hora pico',
    category: 'problema_tienda',
    cases: 29,
    experienceIds: [],
    status: 'publicado',
    protocolId: 'p-011',
    trend: 4,
    zones: ['Chapinero', 'Centro'],
    createdAt: '2026-08-05',
  },
  {
    id: 'cl-4',
    title: 'Entregas lejanas en turno noche',
    category: 'demasiado_lejos',
    cases: 18,
    experienceIds: ['e-3'],
    status: 'publicado',
    protocolId: 'p-017',
    trend: 12,
    zones: ['Usaquén', 'Kennedy'],
    createdAt: '2026-08-22',
  },
  {
    id: 'cl-5',
    title: 'Incentivos que no se reflejan a tiempo',
    category: 'problema_incentivo',
    cases: 15,
    experienceIds: ['e-4'],
    status: 'publicado',
    protocolId: 'p-021',
    trend: -5,
    zones: ['Cedritos', 'Suba'],
    createdAt: '2026-09-01',
  },
  {
    id: 'cl-6',
    title: 'Direcciones confusas en conjuntos cerrados',
    category: 'problema_pedido',
    cases: 12,
    experienceIds: ['e-5'],
    status: 'en_validacion',
    protocolId: 'p-019',
    trend: 21,
    zones: ['Suba', 'Cedritos'],
    createdAt: '2026-09-15',
  },
  {
    id: 'cl-7',
    title: 'Pagos en efectivo sin cambio',
    category: 'problema_pedido',
    cases: 9,
    experienceIds: ['e-10'],
    status: 'protocolo_en_borrador',
    protocolId: 'p-023',
    trend: 30,
    zones: ['Chapinero'],
    createdAt: '2026-09-24',
  },
  {
    id: 'cl-8',
    title: 'Punto de recogida difícil de ubicar',
    category: 'problema_tienda',
    cases: 7,
    experienceIds: [],
    status: 'detectado',
    trend: 40,
    zones: ['Centro'],
    createdAt: '2026-09-27',
  },
];

export const HELP_REQUESTS: HelpRequest[] = [
  {
    id: 'h-1',
    category: 'cliente_no_responde',
    text: 'Llegué a un edificio en la 63 y el cliente no contestaba. Esperé 10 minutos.',
    createdAt: '2026-09-29T08:12:00',
    status: 'resuelto',
    riderName: 'Kevin Martínez',
    zone: 'Kennedy',
    matchedProtocolId: 'p-014',
    similarCount: 37,
    clusterId: 'cl-1',
  },
  {
    id: 'h-2',
    category: 'problema_tienda',
    text: 'La tienda me dijo que el pedido no existía, pero en la app aparecía.',
    createdAt: '2026-09-28T20:40:00',
    status: 'en_revision',
    riderName: 'Natalia Vargas',
    zone: 'Centro',
    matchedProtocolId: 'p-011',
    similarCount: 29,
    clusterId: 'cl-3',
  },
  {
    id: 'h-3',
    category: 'demasiado_lejos',
    text: 'Me asignaron una entrega a 9 km de mi zona al final del turno.',
    createdAt: '2026-09-28T22:15:00',
    status: 'en_revision',
    riderName: 'Kevin Martínez',
    zone: 'Kennedy',
    matchedProtocolId: 'p-017',
    similarCount: 18,
    clusterId: 'cl-4',
  },
  {
    id: 'h-4',
    category: 'problema_pedido',
    text: 'El cliente pagó en efectivo con un billete grande y no tenía cambio.',
    createdAt: '2026-09-28T19:02:00',
    status: 'recibido',
    riderName: 'Sebastián Castro',
    zone: 'Chapinero',
    similarCount: 9,
    clusterId: 'cl-7',
  },
  {
    id: 'h-5',
    category: 'problema_incentivo',
    text: 'Cumplí los pedidos de la campaña del fin de semana y no lo veo en mi resumen.',
    createdAt: '2026-09-27T10:30:00',
    status: 'resuelto',
    riderName: 'Juliana Torres',
    zone: 'Cedritos',
    matchedProtocolId: 'p-021',
    similarCount: 15,
    clusterId: 'cl-5',
  },
  {
    id: 'h-6',
    category: 'problema_tienda',
    text: 'No encontraba la entrada para recoger en un local del Centro, di tres vueltas.',
    createdAt: '2026-09-27T13:45:00',
    status: 'recibido',
    riderName: 'Paola Rincón',
    zone: 'Centro',
    similarCount: 7,
    clusterId: 'cl-8',
  },
  {
    id: 'h-7',
    category: 'otro',
    text: 'Un perro suelto no me dejaba acercarme a la casa.',
    createdAt: '2026-09-26T16:20:00',
    status: 'en_revision',
    riderName: 'Daniela Ortiz',
    zone: 'Teusaquillo',
    similarCount: 11,
  },
  {
    id: 'h-8',
    category: 'cliente_no_responde',
    text: 'Conjunto sin portería, nadie contestaba el citófono.',
    createdAt: '2026-09-26T12:10:00',
    status: 'resuelto',
    riderName: 'Paola Rincón',
    zone: 'Salitre',
    matchedProtocolId: 'p-014',
    similarCount: 37,
    clusterId: 'cl-1',
  },
];

export const INVITATIONS: Invitation[] = [
  {
    id: 'inv-1',
    riderName: 'Tomás Herrera',
    initials: 'TH',
    color: '#E0301A',
    zone: 'Chapinero',
    vehicle: 'moto',
    joinedDaysAgo: 3,
    schedule: ['tarde', 'noche'],
    note: 'Es su primera semana. Se mueve en moto por Chapinero en las tardes, igual que tú.',
    matchScore: 94,
    status: 'pendiente',
  },
  {
    id: 'inv-2',
    riderName: 'Isabela Mora',
    initials: 'IM',
    color: '#12B07A',
    zone: 'Teusaquillo',
    vehicle: 'moto',
    joinedDaysAgo: 5,
    schedule: ['noche'],
    note: 'Trabaja de noche en Teusaquillo, una zona cercana a la tuya.',
    matchScore: 81,
    status: 'pendiente',
  },
];

export const MENTEES: Mentee[] = [
  {
    id: 'me-1',
    name: 'Valentina Ruiz',
    initials: 'VR',
    color: '#FF5B35',
    zone: 'Chapinero',
    vehicle: 'moto',
    week: 2,
    progress: 45,
    lastContact: 'hace 2 días',
    threadId: 'th-valentina',
    mood: 'dudas',
  },
  {
    id: 'me-2',
    name: 'Sebastián Castro',
    initials: 'SC',
    color: '#F5A300',
    zone: 'Chapinero',
    vehicle: 'bici',
    week: 3,
    progress: 60,
    lastContact: 'hace 2 días',
    threadId: 'th-sebastian',
    mood: 'necesita_apoyo',
  },
  {
    id: 'me-3',
    name: 'Daniela Ortiz',
    initials: 'DO',
    color: '#C63010',
    zone: 'Teusaquillo',
    vehicle: 'moto',
    week: 4,
    progress: 85,
    lastContact: 'hace 4 días',
    threadId: 'th-daniela',
    mood: 'bien',
  },
];

export const VOICES: VoiceStory[] = [
  {
    id: 'v-1',
    name: 'Andrés Rojas',
    initials: 'AR',
    color: '#2A78D6',
    badge: 'Copiloto fundador',
    badgeTone: 'brand',
    zone: 'Chapinero',
    months: 38,
    contribution: 'Su experiencia con porterías y clientes que no responden dio origen al Protocolo Crew #014.',
    protocolIds: ['p-014', 'p-011'],
    story:
      'Andrés llegó a Chapinero sin conocer una sola calle. Sus primeras semanas fueron de prueba y error. Hoy acompaña voluntariamente a nuevos Rappitenderos y su forma de manejar las entregas en edificios se convirtió en un protocolo que consultan miles.',
    quote: 'Lo que me costó aprender solo, hoy lo aprende otro en una tarde.',
    accompanied: 14,
    thanks: 212,
  },
  {
    id: 'v-2',
    name: 'Camilo Pérez',
    initials: 'CP',
    color: '#6D55E0',
    badge: 'Guardián nocturno',
    badgeTone: 'grape',
    zone: 'Usaquén',
    months: 51,
    contribution: 'Compartió cómo planear el regreso en entregas lejanas del turno noche.',
    protocolIds: ['p-017'],
    story:
      'Cuatro años de noches en la calle. Camilo empezó a anotar lo que aprendía para no repetir errores; esas notas terminaron siendo la base del protocolo de entregas lejanas.',
    quote: 'De noche, el mejor pedido es el que te deja volver tranquilo.',
    accompanied: 21,
    thanks: 187,
  },
  {
    id: 'v-3',
    name: 'Luisa Fernanda Gómez',
    initials: 'LG',
    color: '#12B07A',
    badge: 'Posta de oro',
    badgeTone: 'sun',
    zone: 'Teusaquillo',
    months: 27,
    contribution: 'Su hábito de revisar la bolsa antes de salir inspiró el Protocolo Crew #009.',
    protocolIds: ['p-009'],
    story:
      'Luisa rueda en bici y es la persona más organizada de la Crew. Su posta sobre pedidos incompletos fue la más agradecida del trimestre.',
    quote: 'Dos minutos en la tienda te ahorran veinte en la puerta.',
    accompanied: 9,
    thanks: 164,
  },
  {
    id: 'v-4',
    name: 'Juliana Torres',
    initials: 'JT',
    color: '#E0301A',
    badge: 'Voz clara',
    badgeTone: 'mint',
    zone: 'Cedritos',
    months: 14,
    contribution: 'Explicó con claridad cómo funcionan los tiempos de actualización de campañas.',
    protocolIds: ['p-021', 'p-014'],
    story:
      'Juliana no es Copiloto, y no hace falta. Compartió su experiencia en Pasa la Posta y ayudó a que cientos de nuevos entendieran algo que generaba mucha desconfianza.',
    quote: 'Preguntar a tiempo evita un mal día.',
    accompanied: 0,
    thanks: 98,
  },
  {
    id: 'v-5',
    name: 'Mateo León',
    initials: 'ML',
    color: '#0A8F62',
    badge: 'Mapa vivo',
    badgeTone: 'sky',
    zone: 'Suba',
    months: 20,
    contribution: 'Sus trucos para conjuntos cerrados están en validación como nuevo protocolo.',
    protocolIds: ['p-006'],
    story:
      'Mateo conoce cada conjunto de Suba. Sus experiencias sobre direcciones confusas se agruparon en un patrón que Rappi está validando.',
    quote: 'La portería sabe más que el mapa.',
    accompanied: 3,
    thanks: 76,
  },
  {
    id: 'v-6',
    name: 'Daniela Ortiz',
    initials: 'DO',
    color: '#C63010',
    badge: 'Primera posta',
    badgeTone: 'brand',
    zone: 'Teusaquillo',
    months: 1,
    contribution: 'Con solo un mes, su experiencia con mascotas en la entrega abrió un nuevo protocolo.',
    protocolIds: [],
    story:
      'Daniela demuestra que cualquiera puede aportar. En su tercera semana compartió una situación que nadie había documentado y hoy es un protocolo en validación.',
    quote: 'No hay que llevar años para enseñar algo.',
    accompanied: 0,
    thanks: 41,
  },
];

export const BENEFITS: Benefit[] = [
  {
    id: 'b-1',
    category: 'movilidad',
    title: 'Descuento en mantenimiento',
    description: 'Tarifas preferenciales en revisión y mantenimiento preventivo de tu vehículo.',
    detail:
      'Aplica en talleres aliados participantes. Incluye revisión de frenos, luces y llantas, pensado para quienes trabajan todos los días en la vía.',
    howTo: ['Registra tu interés.', 'Recibirás los talleres aliados disponibles en tu zona.', 'Presenta tu perfil Crew en el taller.'],
    tag: 'Más solicitado',
  },
  {
    id: 'b-2',
    category: 'movilidad',
    title: 'Kit de seguridad vial',
    description: 'Acceso preferente a elementos reflectivos e impermeables para temporada de lluvias.',
    detail: 'Elementos de visibilidad y protección para moverte más seguro en temporada de lluvia.',
    howTo: ['Registra tu interés.', 'Te avisaremos cuando haya disponibilidad en tu ciudad.'],
    tag: 'Temporada de lluvias',
  },
  {
    id: 'b-3',
    category: 'movilidad',
    title: 'Talleres de conducción segura',
    description: 'Sesiones prácticas sobre manejo defensivo en ciudad.',
    detail: 'Talleres presenciales de 2 horas dictados por instructores aliados.',
    howTo: ['Registra tu interés.', 'Elige la fecha que mejor se acomode a tu turno.'],
    tag: 'Presencial',
  },
  {
    id: 'b-4',
    category: 'salud',
    title: 'Acceso a telemedicina',
    description: 'Consultas médicas generales por videollamada, a la hora que puedas.',
    detail: 'Orientación médica general por videollamada o chat, con horarios extendidos para quienes trabajan de noche.',
    howTo: ['Registra tu interés.', 'Recibirás instrucciones de activación.', 'Agenda desde tu celular.'],
    tag: 'Disponible 24/7',
  },
  {
    id: 'b-5',
    category: 'salud',
    title: 'Orientación en bienestar emocional',
    description: 'Espacios de escucha y orientación con profesionales.',
    detail: 'Sesiones de orientación confidenciales para manejar el estrés del día a día.',
    howTo: ['Registra tu interés.', 'Un profesional aliado te contactará.'],
    tag: 'Confidencial',
  },
  {
    id: 'b-6',
    category: 'salud',
    title: 'Jornadas de salud preventiva',
    description: 'Chequeos básicos en puntos de encuentro de la Crew.',
    detail: 'Toma de presión, glucometría y orientación visual en jornadas periódicas.',
    howTo: ['Registra tu interés.', 'Te avisaremos la próxima jornada en tu zona.'],
    tag: 'Por zonas',
  },
  {
    id: 'b-7',
    category: 'familia',
    title: 'Beneficios educativos',
    description: 'Apoyo para la educación de tus hijos o personas a cargo.',
    detail: 'Acceso a descuentos en útiles escolares y programas de refuerzo escolar con aliados educativos.',
    howTo: ['Registra tu interés.', 'Indica cuántas personas a cargo tienes.'],
    tag: 'Para tu familia',
  },
  {
    id: 'b-8',
    category: 'familia',
    title: 'Telemedicina familiar',
    description: 'Extiende la orientación médica a tu núcleo familiar.',
    detail: 'Consultas generales para hasta 3 personas de tu núcleo familiar.',
    howTo: ['Registra tu interés.', 'Registra a tu familia al activar.'],
    tag: 'Hasta 3 personas',
  },
  {
    id: 'b-9',
    category: 'familia',
    title: 'Planes de recreación',
    description: 'Actividades culturales y recreativas para compartir en familia.',
    detail: 'Acceso preferente a actividades culturales y recreativas con aliados.',
    howTo: ['Registra tu interés.', 'Revisa la agenda mensual.'],
    tag: 'Fines de semana',
  },
  {
    id: 'b-10',
    category: 'aprendizaje',
    title: 'Cursos y capacitación',
    description: 'Cursos cortos en finanzas personales, idiomas y herramientas digitales.',
    detail: 'Formación virtual a tu ritmo, pensada para encajar entre turnos.',
    howTo: ['Registra tu interés.', 'Elige tu ruta de aprendizaje.'],
    tag: 'A tu ritmo',
  },
  {
    id: 'b-11',
    category: 'aprendizaje',
    title: 'Formación para Copilotos',
    description: 'Taller voluntario sobre cómo acompañar y compartir experiencia.',
    detail: 'Un taller opcional para quienes quieran acompañar mejor. No es requisito para ser Copiloto.',
    howTo: ['Registra tu interés.', 'Recibirás la próxima fecha disponible.'],
    tag: 'Opcional',
  },
  {
    id: 'b-12',
    category: 'aprendizaje',
    title: 'Certificado de habilidades',
    description: 'Reconocimiento de las habilidades que desarrollas en la calle.',
    detail: 'Certificación de competencias como servicio al cliente y logística de última milla.',
    howTo: ['Registra tu interés.', 'Completa el módulo de evaluación.'],
    tag: 'Nuevo',
  },
];

// Métricas DEMO para la analítica del panel administrativo.
export const ANALYTICS = {
  kpis: {
    accompanied: 1284,
    accompaniedDelta: 18,
    adoption: 72,
    adoptionDelta: 6,
    reported: 3417,
    reportedDelta: -4,
    protocolsCreated: 24,
    protocolsCreatedDelta: 3,
    protocolsViewed: 18930,
    protocolsViewedDelta: 27,
    resolved: 81,
    resolvedDelta: 5,
    retention30: 78,
    retention30Delta: 9,
    retention60: 64,
    retention60Delta: 11,
    churn: 14,
    churnDelta: -6,
  },
  months: ['Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep'],
  accompaniedByMonth: [92, 138, 176, 214, 297, 367],
  protocolViewsByMonth: [1240, 1890, 2630, 3310, 4420, 5440],
  retention: {
    withCopilot: { d30: 78, d60: 64 },
    withoutCopilot: { d30: 59, d60: 41 },
  },
  churnByMonth: [24, 22, 20, 18, 16, 14],
  problemsByCategory: [
    { category: 'cliente_no_responde', value: 1120 },
    { category: 'problema_tienda', value: 804 },
    { category: 'problema_pedido', value: 672 },
    { category: 'demasiado_lejos', value: 417 },
    { category: 'problema_incentivo', value: 268 },
    { category: 'otro', value: 136 },
  ] as { category: import('./types').HelpCategory; value: number }[],
};

/** Contenido propuesto por Rappi para el patrón usado en el Modo presentación. */
export const PRESENTATION_CLUSTER_ID = 'cl-8';
export const PRESENTATION_EXPERIENCE_IDS = ['e-11', 'e-13', 'e-14'];
export const PRESENTATION_PROTOCOL_PRESET = {
  title: 'Punto de recogida difícil de ubicar',
  category: 'problema_tienda' as const,
  summary: 'Qué hacer cuando no encuentras por dónde recoger el pedido en la tienda.',
  problem:
    'Llegas a la tienda y no encuentras el punto de recogida: la entrada está por detrás, en un parqueadero o en una puerta de servicio.',
  situation:
    'Frecuente en el Centro y en centros comerciales. Los nuevos pierden tiempo dando vueltas y llegan tarde a la entrega.',
  steps: [
    'Antes de llegar, revisa las notas de la tienda en la app: muchas indican la entrada de recogida.',
    'Si no hay indicación, pregunta al vigilante o al personal de la entrada principal por el punto de domiciliarios.',
    'En centros comerciales, busca la puerta de servicio o el sótano antes de entrar por el acceso de clientes.',
    'Si tras unos minutos no lo encuentras, escribe a la tienda por el chat del pedido.',
  ],
  escalate: [
    'Si la tienda no responde y el tiempo de espera supera lo que indica la app.',
    'Si la dirección de la tienda en la app no coincide con la ubicación real.',
  ],
  origin:
    'Construido a partir de experiencias reales de Rappitenderos del Centro y del Salitre, revisado y validado por el equipo de Operaciones de Rappi.',
};

/** Caso de la demo de 40 s del Modo presentación. */
export const DEMO_CASE = {
  category: 'cliente_no_responde' as const,
  protocolId: 'p-014',
  clusterId: 'cl-1',
  text: 'Llegué al edificio, llamé dos veces y el cliente no contesta. En portería no me dejan subir.',
};
